### ISSUE TITLE
Lack of explanation of Advanced settings

### ISSUE THREAD

**Issue by dooniem** [kjeet90/homey-power-of-the-hour#72]
Unsure if this is an issue per se. But here goes.
I'm trying to understand the "advanced section" under settings. Estimation. This is a number from 1 to 1000.
I have the standard settings of "age" as method and "5" as estimation. My guess is that I get better predictions, more updates the higher this number is? At the same time more resource demanding for the Homey? 

Is it as simple as 60 seconds divided into 1000 units, or how should I interpret this setting?

If I'm able to get your attention with this issue. I'm also a bit lost on the settings for "estimation warnings - usage" 
The app comes pre-configured on default settings. I notice the default is to reset a potential estimation warning every hour, independent of the current load. I think I understand the other option, "carry on over to next hour", but struggle to imagine pros and cons for this. I struggle to understand if this setting is something I want to change in one flow, but keep in another flow. In other words I wonder if you could elaborate a bit more on what would make me choose one over the other. 
If I'm not completely wrong, this would mean a 9000W power consumption late in the hour, who triggers the estimation warning, get's reset when a new hour starts. In the same hour a "badly handled" (ie. based too much on price and not on load) car charger start with 5000W, but again the default setting to notify an estimation warning is 30 minutes. Then you're screwed to maintain a goal of 5000Wh that hour? I understand that the usage warning will trigger earlier, but say that limit is 4500Wh, without having done the math, I reckon this happens very early in the hour...

Btw, the explanation text for the  "estimation warnings - usage" -> "reset every hour" refers to "cost warning". You have probably copy/pasted, but it leaves doubt. Is it too much to ask for more explanations in your settings inside the app or in the readme?

**Comment by kjeet90** [comment]
If you click in either one of the advanced settings there is a explanation for each of them.

**Prediction method**: Here you select if your estimation should be done through either the age of your history or x amount of the latest readings. If you select Age (minutes) it will use all readings from your history which is younger than the number set in **History**. So if you select the setting **Age (minutes)** in **Prediction method** and **5** in **History**, which are the default values, it will predict your total consumption based on history from the last five minutes. If you however select **Count** instead, it will use the 5 latest readings to predict your consumption. A higher number in **History** would mean it reacts slower. After much trial and error I concluded that the 5 minute history would work in most cases. If you want a quicker reaction (but this fluctuates alot more, meaning you could get warning and reset triggers quite often) you should adjust this number closer to zero.

This app is meant to give you the option to try to stay below a certain consumption limit every hour, so that is the reason it resets every hour. The app was primarily made from the rules applied here in Norway, which says that if you exceed let's say 5kWh in a single hour you would be charged a higher monthly fee than if you stayed below. So that is the reason why it's only hour-by-hour. I got asked by a guy if I could add a setting where the reset would not trigger on a new hour, but require the predicted consumption to drop below e certain level before resetting (he didn't use it hour-by-hour). So what to use will really depend on what you want to do. If you want to keep below e.g. 5kWh all hours it should NOT be set to carry on to the next hour.

A 9000W power consumption could be just fine late in the hour, it would not necessarily mean the estimation would go above the limit of 4500Wh, it really depends on how much you've used earlier in the hour and how much time if left of the hour. When the warning triggers, you should reduce your consumption, when it drops below your reset limit you can increase your consumption again. This way it would self-regulate to stay within your limits, if your load is not too high, but this is something you need to tweak yourself and see what works best for you.

How the system reacts to price/consumption is up to each and every user to configure, it is impossible to create a solution that works perfect for everyone, so that is why you can configure all these settings to tweak the system to work for you.

Thanks for the input on the reference issue, I will fix this in the next release.

**Comment by dooniem** [comment]
Thanks for all the input. A bit clarifying. I am Norwegian, I just figured English is the GitHub language the same way English is written within Homey’s community forum on Norwegian apps. 
My original concern with resetting the warning every hour was related to using the  flow card “when usage warning reset” inside a flow to regulate a car charger, given that the default notification for triggering the usage warning is 30 minutes. Then you could potentially have a cooking top, an oven and a car charger on max from the get go of the hour and for 30min, making the last 30 minutes of the hour hard to stay under 5kW. 
Relaying on triggered warnings alone, as my first draft did, won’t suffice. You need “well thought through” triggers for remaining effect as well. 

Which brings me to the question, do you, as the creator, have your own idea/road map for when to use all of the different “pieces/triggers”?
I assume since you don’t want to trigger flags before 30mins into the hour by default, you have your own idea for how to use flags. Same way you probably have a thought for when to use estimated used/remaining and actual used/remaining inside your flows?

Just by writing this comment I got a better understanding on when to use “actual remaining power” and “estimated remaining power”. I guess it would be nice to have some more examples written somewhere. Wiki, in-app, or elsewhere. Stopping me and others failing so much before we succeed or give up? 😅

**Comment by kjeet90** [comment]
You can set it to trigger earlier if you want, but I just put 30 minutes as default since in my case (without a car charger) I didn't need it to trigger any earlier than that to be able to stay below the limit. If you experience that there is a issue with you not being able to stay below the limit since it's triggering too late, just reduce 30 to for example 10 or 15 and see if that solves it, or even put it lower. The default values are just what worked for me, and this should be tweaked for every device and its use case.

Personally I don't have much use for this app really, since I don't have a car charger and my house is fairly new, so I will easily stay below the 5kW limit. I just turn down my heated floors if my prediction warning triggers, and turn them back up on reset, using the default settings provided in the app. This means that if I put on a cooking top the floor heating might turn down for a little while, but I barely notice this since the heat loss is so slow.

I do have a wiki in my todo-list, but I don't have much time available for these things right now, and lots of other ongoing projects as well, so it is unfortunately a bit down on my priority list, but it will come eventually. 

The recently added "power available"/"remaining power" should give you a clearer indication of how much you can have on simultaniously to stay within the limit. If you can set your charging current on your charger you can calculate what current you should set the charger to. "Power available" / voltage (400V or 230, depending on what your charger is using) = amperage (formula: I = P / U --> Current = Power / Voltage ). I would recommend to subtract some amps from this value to have some buffer for other things. You can also then compare the power available towards a pulse meter for the entire house and see that if e.g. you have more than 2000 W available (pulse reported power usage - power available from POTH > 2000) you can "safely" turn on e.g. a heating oven that uses let's say 1500W.

**Comment by dooniem** [comment]
Btw, not sure I understand your last formula .Whenever there’s a surplus the result is negative. But I read you as there is some math necessary with the pulse reported power right now to get actual remaining power? Or are you hinting to the need to subtract the current charging power before calculating a new “I” for the charger?

**Comment by kjeet90** [comment]
Sorry, just too much going on at the same time when I replied, ignore the latest formula. Power available is what consumption you can have to reach either the consumption limit or the predicted consumption limit. Why Piggy bank is reporting something else than my app I have no idea about, I haven't looked at his code, but I believe my calculations should be correct to reach the limits exactly. At least that is what my tests have concluded with.

**Comment by kjeet90** [comment]
Made a [Github wiki](https://github.com/kjeet90/homey-power-of-the-hour/wiki) with more information about app and device capabilities
